# Generated by Django 4.2 on 2025-11-22 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0002_alter_property_landlord_id_alter_property_pmc_id'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField()),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('paid_to', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_by_pmc', models.BooleanField(default=False)),
                ('pmc_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('pmc_approval_request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='maintenance.maintenancerequest')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='property.property')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'property_expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['property_id'], name='property_ex_propert_d6b28f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='property_ex_categor_d46097_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='property_ex_date_05fc31_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['created_by'], name='property_ex_created_382b19_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['maintenance_request_id'], name='property_ex_mainten_f45ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['property_id', 'date'], name='property_ex_propert_4416f0_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['pmc_id'], name='property_ex_pmc_id_e91bee_idx'),
        ),
    ]
