# Generated by Django 4.2 on 2025-11-22 02:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Admin'), ('SUPPORT', 'Support'), ('VIEWER', 'Viewer')], default='PLATFORM_ADMIN', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('allowed_google_domains', models.JSONField(blank=True, default=list, help_text="Allowed Google email domains (e.g., ['@gmail.com'])")),
                ('ip_whitelist', models.JSONField(blank=True, default=list, help_text='Allowed IP addresses')),
                ('require_ip_whitelist', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'db_table': 'admins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('resource', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('target_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('target_user_role', models.CharField(blank=True, max_length=50, null=True)),
                ('target_entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_type', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('google_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'db_table': 'admin_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PROPERTY', 'Property'), ('TENANT', 'Tenant'), ('LEASE', 'Lease'), ('PAYMENT', 'Payment'), ('MAINTENANCE', 'Maintenance'), ('LANDLORD', 'Landlord'), ('PMC', 'Property Management Company'), ('ADMIN', 'Admin'), ('SETTINGS', 'Settings')], max_length=50)),
                ('resource', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('READ', 'Read'), ('WRITE', 'Write'), ('DELETE', 'Delete'), ('MANAGE', 'Manage')], max_length=20)),
                ('conditions', models.JSONField(blank=True, help_text='Additional conditions (e.g., scope restrictions)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by_pmc_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('user_type', models.CharField(choices=[('ADMIN', 'Admin'), ('LANDLORD', 'Landlord'), ('TENANT', 'Tenant'), ('PMC', 'Property Management Company'), ('VENDOR', 'Vendor')], max_length=20)),
                ('scope', models.JSONField(blank=True, help_text='Scope restrictions (e.g., specific properties, regions)', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='rbac.role')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'user_roles',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.JSONField(blank=True, null=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rbac.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='roles_name_a96913_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_active'], name='roles_is_acti_723ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['created_by_pmc_id'], name='roles_created_b45fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['category'], name='permissions_categor_b3ddb9_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['resource'], name='permissions_resourc_8c0693_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['action'], name='permissions_action_208379_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('category', 'resource', 'action')},
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='rbac.admin'),
        ),
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['email'], name='admins_email_fe9722_idx'),
        ),
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['role'], name='admins_role_baf3bc_idx'),
        ),
        migrations.AddIndex(
            model_name='admin',
            index=models.Index(fields=['is_active'], name='admins_is_acti_5d7c65_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user_id', 'user_type'], name='user_roles_user_id_742675_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='user_roles_role_id_0b583b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user_id', 'user_type', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['admin'], name='admin_audit_admin_i_cbd562_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['action'], name='admin_audit_action_d6f52c_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['resource'], name='admin_audit_resourc_62162b_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['created_at'], name='admin_audit_created_7f55c8_idx'),
        ),
    ]
