# Generated by Django 4.2 on 2025-11-22 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('PROPERTY_OWNERSHIP', 'Property Ownership'), ('TENANT_DOCUMENT', 'Tenant Document'), ('APPLICATION', 'Application'), ('ENTITY_APPROVAL', 'Entity Approval'), ('FINANCIAL_APPROVAL', 'Financial Approval'), ('INSPECTION', 'Inspection'), ('OTHER', 'Other')], db_index=True, max_length=50)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('requested_by', models.CharField(db_index=True, max_length=100)),
                ('requested_by_role', models.CharField(max_length=20)),
                ('requested_by_email', models.EmailField(max_length=254)),
                ('requested_by_name', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('assigned_to_role', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('assigned_to_name', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_by', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('verified_by_role', models.CharField(blank=True, max_length=20, null=True)),
                ('verified_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('verified_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unified Verification',
                'verbose_name_plural': 'Unified Verifications',
                'db_table': 'unified_verifications',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedVerificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('updated', 'Updated')], db_index=True, max_length=20)),
                ('performed_by', models.CharField(db_index=True, max_length=100)),
                ('performed_by_role', models.CharField(max_length=20)),
                ('performed_by_email', models.EmailField(max_length=254)),
                ('performed_by_name', models.CharField(max_length=255)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='verification.unifiedverification')),
            ],
            options={
                'verbose_name': 'Verification History',
                'verbose_name_plural': 'Verification History',
                'db_table': 'unified_verification_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='unifiedverification',
            index=models.Index(fields=['verification_type', 'status'], name='unified_ver_verific_8cb423_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedverification',
            index=models.Index(fields=['entity_type', 'entity_id'], name='unified_ver_entity__fc6ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedverification',
            index=models.Index(fields=['requested_by', 'status'], name='unified_ver_request_8500a9_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedverification',
            index=models.Index(fields=['verified_by', 'status'], name='unified_ver_verifie_2fc579_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedverification',
            index=models.Index(fields=['assigned_to', 'status'], name='unified_ver_assigne_ec58fd_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedverification',
            index=models.Index(fields=['status', 'priority'], name='unified_ver_status_107fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedverification',
            index=models.Index(fields=['requested_at'], name='unified_ver_request_0e3423_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedverification',
            index=models.Index(fields=['due_date'], name='unified_ver_due_dat_76b296_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unifiedverification',
            unique_together={('verification_type', 'entity_type', 'entity_id')},
        ),
        migrations.AddIndex(
            model_name='unifiedverificationhistory',
            index=models.Index(fields=['verification_id'], name='unified_ver_verific_7b7a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedverificationhistory',
            index=models.Index(fields=['action'], name='unified_ver_action_cfaa8a_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedverificationhistory',
            index=models.Index(fields=['created_at'], name='unified_ver_created_5c4a18_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedverificationhistory',
            index=models.Index(fields=['performed_by'], name='unified_ver_perform_4f8bef_idx'),
        ),
    ]
