/**
 * Generated API Handler for Application
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated from the canonical schema registry.
 * Run `npm run generate:api-handlers` to regenerate.
 * 
 * Generated: 2025-11-18T02:40:03.898Z
 */

import { NextApiRequest, NextApiResponse } from 'next';
import { withAuth, UserContext } from '@/lib/middleware/apiMiddleware';
import { ApplicationService, ApplicationRepository } from '@/lib/domains/application';

import { applicationCreateSchema, applicationUpdateSchema, applicationQuerySchema } from '@/lib/schemas';
const { prisma } = require('@/lib/prisma');

/**
 * API Handler for Application CRUD operations
 */
async function handler(req: NextApiRequest, res: NextApiResponse, user: UserContext) {
  const repository = new ApplicationRepository(prisma);
  const { UnitRepository } = require('@/domains/unit/domain/UnitRepository');
  const unitRepository = new UnitRepository(prisma);
  const service = new ApplicationService(repository, unitRepository);

  try {
    switch (req.method) {
      case 'GET': {
        // List Applications
        if (!req.query.id) {
          const query = applicationQuerySchema.parse(req.query);
          const result = await service.list(query, { unit: true, property: true, lease: true });
          return res.status(200).json({
            success: true,
            data: result.applications || [],
            pagination: result.pagination || { page: 1, limit: 50, total: 0, totalPages: 0 },
          });
        }

        // Get Application by ID
        const id = req.query.id as string;
        const item = await service.getById(id, { unit: true, property: true, lease: true });
        if (!item) {
          return res.status(404).json({ error: 'Application not found' });
        }
        return res.status(200).json({ success: true, data: item });
      }

      case 'POST': {
        const data = applicationCreateSchema.parse(req.body);
        const created = await service.create(data, { userId: user.userId, userRole: user.role });
        return res.status(201).json({ success: true, data: created });
      }

      case 'PATCH': {
        const id = req.query.id as string;
        if (!id) {
          return res.status(400).json({ error: 'ID is required' });
        }
        const data = applicationUpdateSchema.parse(req.body);
        const updated = await service.update(id, data);
        return res.status(200).json({ success: true, data: updated });
      }

      case 'DELETE': {
        const id = req.query.id as string;
        if (!id) {
          return res.status(400).json({ error: 'ID is required' });
        }
        await service.delete(id);
        res.status(204).end();
        return;
      }

      default:
        return res.status(405).json({ error: 'Method not allowed' });
    }
  } catch (error: any) {
    if (error.name === 'ZodError') {
      return res.status(400).json({
        error: 'Validation error',
        details: error.issues,
      });
    }
    console.error(`[Application API Handler] Error:`, error);
    return res.status(500).json({
      error: error.message || 'Internal server error',
    });
  }
}

export default withAuth(handler, {
  requireRole: ['landlord', 'pmc', 'admin'],
  allowedMethods: ['GET', 'POST', 'PATCH', 'DELETE'],
});
