/**
 * Generated API Handlers Index
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated from the canonical schema registry.
 * Run `npm run generate:api-handlers` to regenerate.
 * 
 * Generated: 2025-11-18T02:40:03.900Z
 */

import propertiesHandler from './properties.handler';
import tenantsHandler from './tenants.handler';
import leasesHandler from './leases.handler';
import rentPaymentsHandler from './rentPayments.handler';
import maintenanceHandler from './maintenance.handler';
import documentsHandler from './documents.handler';
import expensesHandler from './expenses.handler';
import inspectionsHandler from './inspections.handler';
import vendorsHandler from './vendors.handler';
import conversationsHandler from './conversations.handler';
import applicationsHandler from './applications.handler';
import notificationsHandler from './notifications.handler';
import tasksHandler from './tasks.handler';
import invitationsHandler from './invitations.handler';
import generatedFormsHandler from './generatedForms.handler';
import unitsHandler from './units.handler';

export const generatedHandlers = {
  properties: propertiesHandler,
  tenants: tenantsHandler,
  leases: leasesHandler,
  rentPayments: rentPaymentsHandler,
  maintenance: maintenanceHandler,
  documents: documentsHandler,
  expenses: expensesHandler,
  inspections: inspectionsHandler,
  vendors: vendorsHandler,
  conversations: conversationsHandler,
  applications: applicationsHandler,
  notifications: notificationsHandler,
  tasks: tasksHandler,
  invitations: invitationsHandler,
  generatedForms: generatedFormsHandler,
  units: unitsHandler,
};

export default generatedHandlers;
