# Generated by Django 4.2 on 2025-11-22 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0002_alter_property_landlord_id_alter_property_pmc_id'),
        ('lease', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('co_applicant_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('screening_requested', models.BooleanField(default=False)),
                ('screening_requested_at', models.DateTimeField(blank=True, null=True)),
                ('screening_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('screening_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20, null=True)),
                ('screening_data', models.JSONField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by_type', models.CharField(blank=True, max_length=20, null=True)),
                ('approved_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('approved_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=100, null=True)),
                ('rejected_by_type', models.CharField(blank=True, max_length=20, null=True)),
                ('rejected_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rejected_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('application_data', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='lease.lease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='property.property')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='property.unit')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['unit_id'], name='application_unit_id_d78c68_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['property_id'], name='application_propert_ab2032_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant_id'], name='application_applica_69ff6a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_e61111_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['deadline'], name='application_deadlin_9f31e8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_archived'], name='application_is_arch_71bf39_idx'),
        ),
    ]
