/**
 * @pinaka/schemas - Published Package
 * 
 * ⭐ CANONICAL SCHEMA PACKAGE ⭐
 * 
 * This package exports:
 * - Generated types from schema registry
 * - Runtime validators (Zod schemas)
 * - Hand-written validators for high-value types
 * 
 * Usage:
 *   import { PropertyCreate, validatePropertyCreate } from '@pinaka/schemas';
 */

// Re-export from schema-types (canonical source)
export * from '@/schema/types/src/generated-types';
// Note: generated-validators.ts may not exist yet - it's generated by generate-validators script
// export * from '@/schema/types/src/generated-validators';

// Export hand-written validators
export * from './validators/properties';
export * from './validators/tenants';
export * from './validators/leases';
export * from './validators/maintenance';
export * from './validators/documents';

// Re-export Zod for convenience
export { z } from 'zod';

