/**
 * Generated API v1 Client
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated from the canonical schema registry.
 * Run `npm run generate:api-client` to regenerate.
 * 
 * Generated: 2025-11-17T23:52:11.489Z
 */

import { apiClient } from '@/lib/utils/api-client';
import type {
  PropertyCreate,
  PropertyUpdate,
  PropertyQuery,
  PropertyResponse,
  PropertyListResponse,
  TenantCreate,
  TenantUpdate,
  TenantQuery,
  TenantResponse,
  TenantListResponse,
  LeaseCreate,
  LeaseUpdate,
  LeaseQuery,
  LeaseResponse,
  LeaseListResponse,
  RentPaymentCreate,
  RentPaymentUpdate,
  RentPaymentQuery,
  RentPaymentResponse,
  RentPaymentListResponse,
  MaintenanceCreate,
  MaintenanceUpdate,
  MaintenanceQuery,
  MaintenanceResponse,
  MaintenanceListResponse,
  DocumentCreate,
  DocumentUpdate,
  DocumentQuery,
  DocumentResponse,
  DocumentListResponse,
  ExpenseCreate,
  ExpenseUpdate,
  ExpenseQuery,
  ExpenseResponse,
  ExpenseListResponse,
  InspectionCreate,
  InspectionUpdate,
  InspectionQuery,
  InspectionResponse,
  InspectionListResponse,
  VendorCreate,
  VendorUpdate,
  VendorQuery,
  VendorResponse,
  VendorListResponse,
  ConversationCreate,
  ConversationUpdate,
  ConversationQuery,
  ConversationResponse,
  ConversationListResponse,
  ApplicationCreate,
  ApplicationUpdate,
  ApplicationQuery,
  ApplicationResponse,
  ApplicationListResponse,
  NotificationCreate,
  NotificationUpdate,
  NotificationQuery,
  NotificationResponse,
  NotificationListResponse,
  TaskCreate,
  TaskUpdate,
  TaskQuery,
  TaskResponse,
  TaskListResponse,
  InvitationCreate,
  InvitationUpdate,
  InvitationQuery,
  InvitationResponse,
  InvitationListResponse,
  GeneratedFormCreate,
  GeneratedFormUpdate,
  GeneratedFormQuery,
  GeneratedFormResponse,
  GeneratedFormListResponse,
  UnitCreate,
  UnitUpdate,
  UnitQuery,
  UnitResponse,
  UnitListResponse,
} from '@/lib/schemas';


/**
 * Generic API resource client
 */
class ApiResource<TCreate, TUpdate, TQuery, TResponse, TListResponse> {
  constructor(private basePath: string) {}

  async list(query?: TQuery): Promise<TListResponse> {
    const queryString = query ? buildQueryString(query as any) : '';
    const response = await apiClient(`/api/v1/${this.basePath}${queryString}`, {
      method: 'GET',
    });
    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error.error || error.message || 'Request failed');
    }
    return response.json();
  }

  async get(id: string): Promise<TResponse> {
    const response = await apiClient(`/api/v1/${this.basePath}/${id}`, {
      method: 'GET',
    });
    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error.error || error.message || 'Request failed');
    }
    return response.json();
  }

  async create(data: TCreate): Promise<TResponse> {
    const response = await apiClient(`/api/v1/${this.basePath}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error.error || error.message || 'Request failed');
    }
    return response.json();
  }

  async update(id: string, data: TUpdate): Promise<TResponse> {
    const response = await apiClient(`/api/v1/${this.basePath}/${id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error.error || error.message || 'Request failed');
    }
    return response.json();
  }

  async delete(id: string): Promise<void> {
    const response = await apiClient(`/api/v1/${this.basePath}/${id}`, {
      method: 'DELETE',
    });
    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error.error || error.message || 'Request failed');
    }
    if (response.status !== 204) {
      await response.json(); // Consume response body
    }
  }
}

/**
 * Build query string from object
 */
function buildQueryString(params: Record<string, any>): string {
  const searchParams = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined && value !== null) {
      if (Array.isArray(value)) {
        value.forEach((v) => searchParams.append(key, String(v)));
      } else {
        searchParams.append(key, String(value));
      }
    }
  }
  const queryString = searchParams.toString();
  return queryString ? `?${queryString}` : '';
}



/**
 * Specialized API endpoints (non-CRUD)
 */
class SpecializedApi {

  // Analytics

  async propertyperformance(query?: any): Promise<any> {
    const queryString = query ? buildQueryString(query) : '';
    const response = await apiClient(`/api/v1/analytics/property-performance${queryString}`, {
      method: 'GET',
    });
    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error.error || error.message || 'Request failed');
    }
    return response.json();
  }

  async portfolioperformance(query?: any): Promise<any> {
    const queryString = query ? buildQueryString(query) : '';
    const response = await apiClient(`/api/v1/analytics/portfolio-performance${queryString}`, {
      method: 'GET',
    });
    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error.error || error.message || 'Request failed');
    }
    return response.json();
  }

  async tenantdelinquencyrisk(query?: any): Promise<any> {
    const queryString = query ? buildQueryString(query) : '';
    const response = await apiClient(`/api/v1/analytics/tenant-delinquency-risk${queryString}`, {
      method: 'GET',
    });
    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error.error || error.message || 'Request failed');
    }
    return response.json();
  }

  async cashflowforecast(query?: any): Promise<any> {
    const queryString = query ? buildQueryString(query) : '';
    const response = await apiClient(`/api/v1/analytics/cash-flow-forecast${queryString}`, {
      method: 'GET',
    });
    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error.error || error.message || 'Request failed');
    }
    return response.json();
  }
}

/**
 * Generated v1 API Client
 */
export const v1Api = {
  properties: new ApiResource<PropertyCreate, PropertyUpdate, PropertyQuery, PropertyResponse, PropertyListResponse>('properties'),
  tenants: new ApiResource<TenantCreate, TenantUpdate, TenantQuery, TenantResponse, TenantListResponse>('tenants'),
  leases: new ApiResource<LeaseCreate, LeaseUpdate, LeaseQuery, LeaseResponse, LeaseListResponse>('leases'),
  rentPayments: new ApiResource<RentPaymentCreate, RentPaymentUpdate, RentPaymentQuery, RentPaymentResponse, RentPaymentListResponse>('rent-payments'),
  maintenance: new ApiResource<MaintenanceCreate, MaintenanceUpdate, MaintenanceQuery, MaintenanceResponse, MaintenanceListResponse>('maintenance'),
  documents: new ApiResource<DocumentCreate, DocumentUpdate, DocumentQuery, DocumentResponse, DocumentListResponse>('documents'),
  expenses: new ApiResource<ExpenseCreate, ExpenseUpdate, ExpenseQuery, ExpenseResponse, ExpenseListResponse>('expenses'),
  inspections: new ApiResource<InspectionCreate, InspectionUpdate, InspectionQuery, InspectionResponse, InspectionListResponse>('inspections'),
  vendors: new ApiResource<VendorCreate, VendorUpdate, VendorQuery, VendorResponse, VendorListResponse>('vendors'),
  conversations: new ApiResource<ConversationCreate, ConversationUpdate, ConversationQuery, ConversationResponse, ConversationListResponse>('conversations'),
  applications: new ApiResource<ApplicationCreate, ApplicationUpdate, ApplicationQuery, ApplicationResponse, ApplicationListResponse>('applications'),
  notifications: new ApiResource<NotificationCreate, NotificationUpdate, NotificationQuery, NotificationResponse, NotificationListResponse>('notifications'),
  tasks: new ApiResource<TaskCreate, TaskUpdate, TaskQuery, TaskResponse, TaskListResponse>('tasks'),
  invitations: new ApiResource<InvitationCreate, InvitationUpdate, InvitationQuery, InvitationResponse, InvitationListResponse>('invitations'),
  generatedForms: new ApiResource<GeneratedFormCreate, GeneratedFormUpdate, GeneratedFormQuery, GeneratedFormResponse, GeneratedFormListResponse>('generated-forms'),
  units: new ApiResource<UnitCreate, UnitUpdate, UnitQuery, UnitResponse, UnitListResponse>('units'),
  specialized: new SpecializedApi(),
};

export default v1Api;
