/**
 * Generated Server Stub for Document
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated from @pinaka/schema.
 * Run `npm run generate:stubs` to regenerate.
 * 
 * Generated: 2025-11-18T03:19:08.325Z
 */

import { NextApiRequest, NextApiResponse } from 'next';
import { withAuth, UserContext } from '@/lib/middleware/apiMiddleware';
import { DocumentService, DocumentRepository } from '@/lib/domains/document';
import { 
  documentsCreateSchema, 
  documentsUpdateSchema, 
  documentsQuerySchema 
} from '@pinaka/schema';
import { z } from 'zod';
const { prisma } = require('@/lib/prisma');

/**
 * API Handler for Document CRUD operations
 */
async function handler(req: NextApiRequest, res: NextApiResponse, user: UserContext) {
  const repository = new DocumentRepository(prisma);
  const service = new DocumentService(repository);

  try {
    switch (req.method) {
      case 'GET': {
        // List Documents
        if (!req.query.id) {
          const query = documentsQuerySchema.parse(req.query);
          const result = await service.list(query, user);
          return res.status(200).json({
            success: true,
            data: result.data,
            pagination: result.pagination,
          });
        }

        // Get Document by ID
        const id = req.query.id as string;
        const item = await service.getById(id, user);
        if (!item) {
          return res.status(404).json({ error: 'Document not found' });
        }
        return res.status(200).json({ success: true, data: item });
      }

      case 'POST': {
        const data = documentsCreateSchema.parse(req.body);
        const created = await service.create(data, user);
        return res.status(201).json({ success: true, data: created });
      }

      case 'PATCH': {
        const id = req.query.id as string;
        if (!id) {
          return res.status(400).json({ error: 'ID is required' });
        }
        const data = documentsUpdateSchema.parse(req.body);
        const updated = await service.update(id, data, user);
        return res.status(200).json({ success: true, data: updated });
      }

      case 'DELETE': {
        const id = req.query.id as string;
        if (!id) {
          return res.status(400).json({ error: 'ID is required' });
        }
        await service.delete(id, user);
        return res.status(204).send();
      }

      default:
        return res.status(405).json({ error: 'Method not allowed' });
    }
  } catch (error: any) {
    if (error.name === 'ZodError') {
      return res.status(400).json({
        error: 'Validation error',
        details: error.errors,
      });
    }
    console.error(`[Document API Handler] Error:`, error);
    return res.status(500).json({
      error: error.message || 'Internal server error',
    });
  }
}

export default withAuth(handler, {
  requireRole: ['landlord', 'pmc', 'admin'],
  allowedMethods: ["GET","POST","PATCH","DELETE"],
});
