/**
 * Generated Server Stubs Index
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated from @pinaka/schema.
 * Run `npm run generate:stubs` to regenerate.
 * 
 * Generated: 2025-11-18T23:18:22.775Z
 */

import propertiesStub from './properties.stub';
import tenantsStub from './tenants.stub';
import leasesStub from './leases.stub';
import rentPaymentsStub from './rentPayments.stub';
import maintenanceStub from './maintenance.stub';
import documentsStub from './documents.stub';
import expensesStub from './expenses.stub';
import inspectionsStub from './inspections.stub';
import vendorsStub from './vendors.stub';
import conversationsStub from './conversations.stub';
import applicationsStub from './applications.stub';
import notificationsStub from './notifications.stub';
import tasksStub from './tasks.stub';
import invitationsStub from './invitations.stub';
import generatedFormsStub from './generatedForms.stub';
import unitsStub from './units.stub';
import landlordsStub from './landlords.stub';

export const serverStubs = {
  properties: propertiesStub,
  tenants: tenantsStub,
  leases: leasesStub,
  rentPayments: rentPaymentsStub,
  maintenance: maintenanceStub,
  documents: documentsStub,
  expenses: expensesStub,
  inspections: inspectionsStub,
  vendors: vendorsStub,
  conversations: conversationsStub,
  applications: applicationsStub,
  notifications: notificationsStub,
  tasks: tasksStub,
  invitations: invitationsStub,
  generatedForms: generatedFormsStub,
  units: unitsStub,
  landlords: landlordsStub,
};

export default serverStubs;
