/**
 * Generated Server Stubs Index
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated from @pinaka/schema.
 * Run `npm run generate:stubs` to regenerate.
 * 
 * Generated: 2025-11-18T03:19:08.327Z
 */

import propertiesStub from './generated-stubs/properties.stub';
import tenantsStub from './generated-stubs/tenants.stub';
import leasesStub from './generated-stubs/leases.stub';
import rentPaymentsStub from './generated-stubs/rentPayments.stub';
import maintenanceStub from './generated-stubs/maintenance.stub';
import documentsStub from './generated-stubs/documents.stub';
import expensesStub from './generated-stubs/expenses.stub';
import inspectionsStub from './generated-stubs/inspections.stub';
import vendorsStub from './generated-stubs/vendors.stub';
import conversationsStub from './generated-stubs/conversations.stub';
import applicationsStub from './generated-stubs/applications.stub';
import notificationsStub from './generated-stubs/notifications.stub';
import tasksStub from './generated-stubs/tasks.stub';
import invitationsStub from './generated-stubs/invitations.stub';
import generatedFormsStub from './generated-stubs/generatedForms.stub';
import unitsStub from './generated-stubs/units.stub';

export const serverStubs = {
  properties: propertiesStub,
  tenants: tenantsStub,
  leases: leasesStub,
  rentPayments: rentPaymentsStub,
  maintenance: maintenanceStub,
  documents: documentsStub,
  expenses: expensesStub,
  inspections: inspectionsStub,
  vendors: vendorsStub,
  conversations: conversationsStub,
  applications: applicationsStub,
  notifications: notificationsStub,
  tasks: tasksStub,
  invitations: invitationsStub,
  generatedForms: generatedFormsStub,
  units: unitsStub,
};

export default serverStubs;
