# Generated by Django 4.2 on 2025-11-21 23:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lease', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('property_id', models.CharField(db_index=True, max_length=50)),
                ('category', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('REPAIR', 'Repair'), ('UTILITIES', 'Utilities'), ('INSURANCE', 'Insurance'), ('PROPERTY_TAX', 'Property Tax'), ('MANAGEMENT_FEE', 'Management Fee'), ('LEGAL', 'Legal'), ('MARKETING', 'Marketing'), ('OTHER', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('expense_date', models.DateField()),
                ('description', models.TextField()),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('REIMBURSED', 'Reimbursed')], default='PAID', max_length=20)),
                ('maintenance_request_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='SecurityDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('RETURNED', 'Returned'), ('PARTIALLY_RETURNED', 'Partially Returned'), ('FORFEITED', 'Forfeited')], default='HELD', max_length=20)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('amount_returned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_deducted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('deduction_reason', models.TextField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, max_length=500, null=True)),
                ('return_receipt_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_deposits', to='lease.lease')),
            ],
            options={
                'verbose_name': 'Security Deposit',
                'verbose_name_plural': 'Security Deposits',
                'db_table': 'security_deposits',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('E_TRANSFER', 'E-Transfer'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='E_TRANSFER', max_length=50)),
                ('payment_for_month', models.DateField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('OVERDUE', 'Overdue'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PAID', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('late_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.CharField(blank=True, max_length=50, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='lease.lease')),
            ],
            options={
                'verbose_name': 'Rent Payment',
                'verbose_name_plural': 'Rent Payments',
                'db_table': 'rent_payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['property_id'], name='expenses_propert_7de532_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='expenses_categor_a6f264_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='expenses_expense_43600a_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status'], name='expenses_status_86293f_idx'),
        ),
        migrations.AddIndex(
            model_name='securitydeposit',
            index=models.Index(fields=['lease'], name='security_de_lease_i_ab61e0_idx'),
        ),
        migrations.AddIndex(
            model_name='securitydeposit',
            index=models.Index(fields=['status'], name='security_de_status_a3e060_idx'),
        ),
        migrations.AddIndex(
            model_name='securitydeposit',
            index=models.Index(fields=['received_date'], name='security_de_receive_9e2b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['lease'], name='rent_paymen_lease_i_b71699_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['payment_date'], name='rent_paymen_payment_0ccac6_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['payment_for_month'], name='rent_paymen_payment_1cdb29_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['status'], name='rent_paymen_status_51c70c_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['created_at'], name='rent_paymen_created_b131ad_idx'),
        ),
    ]
