# Generated by Django 4.2 on 2025-11-21 23:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('property_name', models.CharField(help_text='Name of the property', max_length=255)),
                ('address_line1', models.CharField(help_text='Street address line 1', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', help_text='Street address line 2 (optional)', max_length=255)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('province_state', models.CharField(help_text='Province or State', max_length=100)),
                ('postal_zip', models.CharField(help_text='Postal or ZIP code', max_length=20)),
                ('country', models.CharField(default='Canada', help_text='Country', max_length=100)),
                ('property_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('MIXED', 'Mixed Use'), ('INDUSTRIAL', 'Industrial')], default='RESIDENTIAL', help_text='Type of property', max_length=50)),
                ('unit_count', models.IntegerField(default=1, help_text='Total number of units', validators=[django.core.validators.MinValueValidator(1)])),
                ('year_built', models.IntegerField(blank=True, help_text='Year the property was built', null=True)),
                ('square_footage', models.DecimalField(blank=True, decimal_places=2, help_text='Total square footage', max_digits=10, null=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, help_text='Lot size in square feet', max_digits=10, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price', max_digits=15, null=True)),
                ('purchase_date', models.DateField(blank=True, help_text='Date property was purchased', null=True)),
                ('assessed_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current assessed value', max_digits=15, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Property description')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes')),
                ('image_url', models.URLField(blank=True, default='', help_text='Primary property image URL', max_length=500)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SOLD', 'Sold'), ('MAINTENANCE', 'Under Maintenance')], default='ACTIVE', help_text='Property status', max_length=20)),
                ('landlord_id', models.UUIDField(help_text='Landlord who owns this property')),
                ('pmc_id', models.UUIDField(blank=True, help_text='Property Management Company (if managed)', null=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('unit_name', models.CharField(help_text="Unit identifier (e.g., 'Unit 101', 'Suite A')", max_length=100)),
                ('bedrooms', models.IntegerField(default=1, help_text='Number of bedrooms', validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1.0, help_text='Number of bathrooms', max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('square_feet', models.DecimalField(blank=True, decimal_places=2, help_text='Unit square footage', max_digits=8, null=True)),
                ('floor_number', models.IntegerField(blank=True, help_text='Floor number', null=True)),
                ('rent_price', models.DecimalField(decimal_places=2, help_text='Monthly rent price', max_digits=10)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, help_text='Security deposit amount', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance'), ('RESERVED', 'Reserved')], default='VACANT', help_text='Unit status', max_length=20)),
                ('has_parking', models.BooleanField(default=False, help_text='Has parking space')),
                ('has_storage', models.BooleanField(default=False, help_text='Has storage unit')),
                ('has_balcony', models.BooleanField(default=False, help_text='Has balcony')),
                ('is_furnished', models.BooleanField(default=False, help_text='Is furnished')),
                ('pets_allowed', models.BooleanField(default=False, help_text='Pets allowed')),
                ('description', models.TextField(blank=True, default='', help_text='Unit description')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes')),
                ('property', models.ForeignKey(help_text='Property this unit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='property.property')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'units',
                'ordering': ['property', 'unit_name'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['landlord_id'], name='properties_landlor_736d10_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['pmc_id'], name='properties_pmc_id_381bca_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='properties_city_c34f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='properties_propert_f38ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties_status_e6008a_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['property', 'status'], name='units_propert_73e07d_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['status'], name='units_status_eafada_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('property', 'unit_name')},
        ),
    ]
