# Generated by Django 4.2 on 2025-11-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='landlord_id',
            field=models.CharField(help_text='Landlord who owns this property', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='pmc_id',
            field=models.CharField(blank=True, help_text='Property Management Company (if managed)', max_length=100, null=True),
        ),
    ]
