# Generated by Django 4.2 on 2025-11-22 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0002_alter_property_landlord_id_alter_property_pmc_id'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('storage_path', models.CharField(max_length=500)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('uploaded_by_email', models.EmailField(max_length=254)),
                ('uploaded_by_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_landlord_delete', models.BooleanField(default=True)),
                ('can_tenant_delete', models.BooleanField(default=True)),
                ('visibility', models.CharField(choices=[('shared', 'Shared'), ('private', 'Private'), ('public', 'Public')], default='shared', max_length=20)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('verification_comment', models.TextField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=100, null=True)),
                ('rejected_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rejected_by_role', models.CharField(blank=True, max_length=50, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_required', models.BooleanField(db_index=True, default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('deleted_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deletion_reason', models.TextField(blank=True, null=True)),
                ('document_hash', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='property.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sender_role', models.CharField(db_index=True, max_length=50)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='document.document')),
            ],
            options={
                'verbose_name': 'Document Message',
                'verbose_name_plural': 'Document Messages',
                'db_table': 'document_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('performed_by', models.CharField(max_length=100)),
                ('performed_by_email', models.EmailField(max_length=254)),
                ('performed_by_name', models.CharField(max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='document.document')),
            ],
            options={
                'verbose_name': 'Document Audit Log',
                'verbose_name_plural': 'Document Audit Logs',
                'db_table': 'document_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='documentmessage',
            index=models.Index(fields=['document_id'], name='document_me_documen_377a87_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmessage',
            index=models.Index(fields=['document_id', 'is_read'], name='document_me_documen_743989_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmessage',
            index=models.Index(fields=['is_read'], name='document_me_is_read_1ccb29_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmessage',
            index=models.Index(fields=['sender_role'], name='document_me_sender__04c624_idx'),
        ),
        migrations.AddIndex(
            model_name='documentauditlog',
            index=models.Index(fields=['action'], name='document_au_action_43d50b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentauditlog',
            index=models.Index(fields=['document_id'], name='document_au_documen_6f8d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category'], name='documents_categor_f8ad6f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expiration_date'], name='documents_expirat_e43349_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_deleted'], name='documents_is_dele_636b14_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_required'], name='documents_is_requ_25245c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_verified'], name='documents_is_veri_fb0cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant_id'], name='documents_tenant__ad8c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant_id', 'is_deleted'], name='documents_tenant__953d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_at'], name='documents_uploade_d6a956_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant_id', 'category'], name='documents_tenant__af78d5_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['property_id'], name='documents_propert_05f5d3_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['property_id', 'is_deleted'], name='documents_propert_24e8fd_idx'),
        ),
    ]
