# Generated by Django 4.2 on 2025-11-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('feature_tenant_invitations', models.BooleanField(default=True)),
                ('feature_document_vault', models.BooleanField(default=True)),
                ('feature_maintenance_requests', models.BooleanField(default=True)),
                ('feature_rent_payments', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_provider', models.CharField(default='gmail', max_length=50)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('notification_channels', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
                'db_table': 'platform_settings',
            },
        ),
    ]
