# Generated by Django 4.2 on 2025-11-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('user_role', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant'), ('pmc', 'Property Management Company'), ('admin', 'Admin')], db_index=True, max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(choices=[('rent_due', 'Rent Due'), ('rent_overdue', 'Rent Overdue'), ('maintenance_update', 'Maintenance Update'), ('approval_request', 'Approval Request'), ('document_expiring', 'Document Expiring'), ('lease_renewal', 'Lease Renewal'), ('payment_received', 'Payment Received'), ('message_received', 'Message Received'), ('ticket_update', 'Ticket Update'), ('verification_status', 'Verification Status'), ('other', 'Other')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('user_role', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant'), ('pmc', 'Property Management Company'), ('admin', 'Admin')], db_index=True, max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(max_length=50)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('send_before_days', models.IntegerField(blank=True, null=True)),
                ('send_on_day', models.BooleanField(default=True)),
                ('send_after_days', models.IntegerField(blank=True, null=True)),
                ('quiet_hours_start', models.CharField(blank=True, max_length=5, null=True)),
                ('quiet_hours_end', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user_id', 'user_role'], name='notificatio_user_id_78bb78_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_b3f2fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user_id', 'user_role', 'notification_type')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user_id', 'user_role'], name='notificatio_user_id_1fce52_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['entity_type', 'entity_id'], name='notificatio_entity__519f8a_idx'),
        ),
    ]
