/**
 * Generated API v1 Client
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated from the canonical schema registry.
 * Run `npm run generate:api-client` to regenerate.
 * 
 * Generated: 2025-11-17T23:52:11.489Z
 */

import { apiClient } from '@/lib/utils/api-client';
import type {
  PropertyCreate,
  PropertyUpdate,
  PropertyQuery,
  PropertyResponse,
  PropertyListResponse,
  TenantCreate,
  TenantUpdate,
  TenantQuery,
  TenantResponse,
  TenantListResponse,
  LeaseCreate,
  LeaseUpdate,
  LeaseQuery,
  LeaseResponse,
  LeaseListResponse,
  RentPaymentCreate,
  RentPaymentUpdate,
  RentPaymentQuery,
  RentPaymentResponse,
  RentPaymentListResponse,
  MaintenanceCreate,
  MaintenanceUpdate,
  MaintenanceQuery,
  MaintenanceResponse,
  MaintenanceListResponse,
  DocumentCreate,
  DocumentUpdate,
  DocumentQuery,
  DocumentResponse,
  DocumentListResponse,
  ExpenseCreate,
  ExpenseUpdate,
  ExpenseQuery,
  ExpenseResponse,
  ExpenseListResponse,
  InspectionCreate,
  InspectionUpdate,
  InspectionQuery,
  InspectionResponse,
  InspectionListResponse,
  VendorCreate,
  VendorUpdate,
  VendorQuery,
  VendorResponse,
  VendorListResponse,
  ConversationCreate,
  ConversationUpdate,
  ConversationQuery,
  ConversationResponse,
  ConversationListResponse,
  ApplicationCreate,
  ApplicationUpdate,
  ApplicationQuery,
  ApplicationResponse,
  ApplicationListResponse,
  NotificationCreate,
  NotificationUpdate,
  NotificationQuery,
  NotificationResponse,
  NotificationListResponse,
  TaskCreate,
  TaskUpdate,
  TaskQuery,
  TaskResponse,
  TaskListResponse,
  InvitationCreate,
  InvitationUpdate,
  InvitationQuery,
  InvitationResponse,
  InvitationListResponse,
  GeneratedFormCreate,
  GeneratedFormUpdate,
  GeneratedFormQuery,
  GeneratedFormResponse,
  GeneratedFormListResponse,
  UnitCreate,
  UnitUpdate,
  UnitQuery,
  UnitResponse,
  UnitListResponse,
  LandlordCreate,
  LandlordUpdate,
  LandlordQuery,
  LandlordResponse,
  LandlordListResponse,
} from '@/lib/schemas';


/**
 * Generic API resource client
 */
class ApiResource<TCreate, TUpdate, TQuery, TResponse, TListResponse> {
  constructor(private basePath: string) {}

  async list(query?: TQuery): Promise<TListResponse> {
    const queryString = query ? buildQueryString(query as any) : '';
    const response = await apiClient(`/api/v1/${this.basePath}${queryString}`, {
      method: 'GET',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  async get(id: string): Promise<TResponse> {
    const response = await apiClient(`/api/v1/${this.basePath}/${id}`, {
      method: 'GET',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  async create(data: TCreate): Promise<TResponse> {
    const response = await apiClient(`/api/v1/${this.basePath}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    const responseData = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(responseData.error || responseData.message || 'Request failed');
    }
    return responseData;
  }

  async update(id: string, data: TUpdate): Promise<TResponse> {
    const response = await apiClient(`/api/v1/${this.basePath}/${id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    const responseData = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(responseData.error || responseData.message || 'Request failed');
    }
    return responseData;
  }

  async delete(id: string): Promise<void> {
    const response = await apiClient(`/api/v1/${this.basePath}/${id}`, {
      method: 'DELETE',
    });
    if (response.status !== 204) {
      const responseData = await response.json().catch(() => ({}));
      if (!response.ok) {
        throw new Error(responseData.error || responseData.message || 'Request failed');
      }
    }
  }
}

/**
 * Build query string from object
 */
function buildQueryString(params: Record<string, any>): string {
  const searchParams = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined && value !== null) {
      if (Array.isArray(value)) {
        value.forEach((v) => searchParams.append(key, String(v)));
      } else {
        searchParams.append(key, String(value));
      }
    }
  }
  const queryString = searchParams.toString();
  return queryString ? `?${queryString}` : '';
}



/**
 * Specialized API endpoints (non-CRUD)
 */
class SpecializedApi {

  // Analytics

  async propertyperformance(query?: any): Promise<any> {
    const queryString = query ? buildQueryString(query) : '';
    const response = await apiClient(`/api/v1/analytics/property-performance${queryString}`, {
      method: 'GET',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  async portfolioperformance(query?: any): Promise<any> {
    const queryString = query ? buildQueryString(query) : '';
    const response = await apiClient(`/api/v1/analytics/portfolio-performance${queryString}`, {
      method: 'GET',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  async tenantdelinquencyrisk(query?: any): Promise<any> {
    const queryString = query ? buildQueryString(query) : '';
    const response = await apiClient(`/api/v1/analytics/tenant-delinquency-risk${queryString}`, {
      method: 'GET',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  async cashflowforecast(query?: any): Promise<any> {
    const queryString = query ? buildQueryString(query) : '';
    const response = await apiClient(`/api/v1/analytics/cash-flow-forecast${queryString}`, {
      method: 'GET',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  // Public Invitations
  async getPublicInvitationByToken(token: string): Promise<any> {
    const response = await apiClient(`/api/v1/public/invitations/${token}`, {
      method: 'GET',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  async acceptPublicInvitation(token: string, formData: any): Promise<any> {
    const response = await apiClient(`/api/v1/public/invitations/accept`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ token, formData }),
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  // User Status
  async getUserStatus(): Promise<any> {
    const response = await apiClient(`/api/v1/user/status`, {
      method: 'GET',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  // Tenant Invitations
  async listTenantInvitations(query?: any): Promise<any> {
    const queryString = query ? buildQueryString(query) : '';
    const response = await apiClient(`/api/v1/tenants/invitations${queryString}`, {
      method: 'GET',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  async createTenantInvitation(data: any): Promise<any> {
    const response = await apiClient(`/api/v1/tenants/invitations`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    const responseData = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(responseData.error || responseData.message || 'Request failed');
    }
    return responseData;
  }

  async getTenantInvitationById(id: string): Promise<any> {
    const response = await apiClient(`/api/v1/tenants/invitations/${id}`, {
      method: 'GET',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  async resendTenantInvitation(id: string): Promise<any> {
    const response = await apiClient(`/api/v1/tenants/invitations/${id}/resend`, {
      method: 'POST',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  async cancelTenantInvitation(id: string): Promise<any> {
    const response = await apiClient(`/api/v1/tenants/invitations/${id}`, {
      method: 'DELETE',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  // Notifications
  async markAllNotificationsAsRead(): Promise<any> {
    const response = await apiClient(`/api/v1/notifications/read-all`, {
      method: 'PUT',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  // Rent Payment Actions
  async sendRentPaymentReceipt(id: string): Promise<any> {
    const response = await apiClient(`/api/v1/rent-payments/${id}/send-receipt`, {
      method: 'POST',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  async markRentPaymentUnpaid(id: string): Promise<any> {
    const response = await apiClient(`/api/v1/rent-payments/${id}/mark-unpaid`, {
      method: 'POST',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  // Conversation Messages
  async sendConversationMessage(conversationId: string, messageText: string): Promise<any> {
    const response = await apiClient(`/api/v1/conversations/${conversationId}/messages`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ messageText }),
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  // Maintenance Actions
  async addMaintenanceComment(id: string, comment: string, authorInfo?: any): Promise<any> {
    const response = await apiClient(`/api/v1/maintenance/${id}/comments`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ comment, ...authorInfo }),
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  async markMaintenanceViewed(id: string, role: string): Promise<any> {
    const response = await apiClient(`/api/v1/maintenance/${id}/mark-viewed`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ role }),
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  async approveMaintenance(id: string, data?: any): Promise<any> {
    const response = await apiClient(`/api/v1/maintenance/${id}/approve`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data || {}),
    });
    const responseData = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(responseData.error || responseData.message || 'Request failed');
    }
    return responseData;
  }

  // Document & File Viewing
  async viewDocument(id: string, fileIndex?: number, versionIndex?: number): Promise<Response> {
    const params = new URLSearchParams();
    if (fileIndex !== undefined) params.append('fileIndex', fileIndex.toString());
    if (versionIndex !== undefined) params.append('versionIndex', versionIndex.toString());
    const queryString = params.toString() ? `?${params.toString()}` : '';
    return apiClient(`/api/v1/documents/${id}/view${queryString}`, {
      method: 'GET',
    });
  }

  async viewRentPaymentReceipt(id: string): Promise<Response> {
    return apiClient(`/api/v1/rent-payments/${id}/view-receipt`, {
      method: 'GET',
    });
  }

  async downloadMaintenancePDF(id: string): Promise<Response> {
    return apiClient(`/api/v1/maintenance/${id}/download-pdf`, {
      method: 'GET',
    });
  }

  async previewForm(id: string): Promise<Response> {
    return apiClient(`/api/v1/forms/generated/${id}/preview`, {
      method: 'GET',
    });
  }

  // Document Messages
  async getDocumentMessages(documentId: string): Promise<any> {
    const response = await apiClient(`/api/v1/documents/${documentId}/messages`, {
      method: 'GET',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  async sendDocumentMessage(documentId: string, message: string): Promise<any> {
    const response = await apiClient(`/api/v1/documents/${documentId}/messages`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ message }),
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  // Invitation Application
  async getInvitationApplication(invitationId: string): Promise<any> {
    const response = await apiClient(`/api/v1/invitations/${invitationId}/application`, {
      method: 'GET',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  // Tenant Payment History
  async getTenantPaymentHistory(): Promise<any> {
    const response = await apiClient(`/api/v1/tenants/payments`, {
      method: 'GET',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  // Analytics Export
  async exportAnalytics(query: any): Promise<Response> {
    const queryString = query ? buildQueryString(query) : '';
    return apiClient(`/api/v1/analytics/export${queryString}`, {
      method: 'GET',
    });
  }

  // Tenants with Outstanding Balance
  async getTenantsWithOutstandingBalance(): Promise<any> {
    const response = await apiClient(`/api/v1/tenants/with-outstanding-balance`, {
      method: 'GET',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  // Tenant Rent Data
  async getTenantRentData(tenantId: string): Promise<any> {
    const response = await apiClient(`/api/v1/tenants/${tenantId}/rent-data`, {
      method: 'GET',
    });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(data.error || data.message || 'Request failed');
    }
    return data;
  }

  // Application Actions
  async approveApplication(id: string, data?: any): Promise<any> {
    const response = await apiClient(`/api/v1/applications/${id}/approve`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data || {}),
    });
    const responseData = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(responseData.error || responseData.message || 'Request failed');
    }
    return responseData;
  }

  async rejectApplication(id: string, reason: string): Promise<any> {
    const response = await apiClient(`/api/v1/applications/${id}/reject`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ reason }),
    });
    const responseData = await response.json().catch(() => ({}));
    if (!response.ok) {
      throw new Error(responseData.error || responseData.message || 'Request failed');
    }
    return responseData;
  }
}

/**
 * Generated v1 API Client
 */
export const v1Api = {
  properties: new ApiResource<PropertyCreate, PropertyUpdate, PropertyQuery, PropertyResponse, PropertyListResponse>('properties'),
  tenants: new ApiResource<TenantCreate, TenantUpdate, TenantQuery, TenantResponse, TenantListResponse>('tenants'),
  leases: new ApiResource<LeaseCreate, LeaseUpdate, LeaseQuery, LeaseResponse, LeaseListResponse>('leases'),
  rentPayments: new ApiResource<RentPaymentCreate, RentPaymentUpdate, RentPaymentQuery, RentPaymentResponse, RentPaymentListResponse>('rent-payments'),
  maintenance: new ApiResource<MaintenanceCreate, MaintenanceUpdate, MaintenanceQuery, MaintenanceResponse, MaintenanceListResponse>('maintenance'),
  documents: new ApiResource<DocumentCreate, DocumentUpdate, DocumentQuery, DocumentResponse, DocumentListResponse>('documents'),
  expenses: new ApiResource<ExpenseCreate, ExpenseUpdate, ExpenseQuery, ExpenseResponse, ExpenseListResponse>('expenses'),
  inspections: new ApiResource<InspectionCreate, InspectionUpdate, InspectionQuery, InspectionResponse, InspectionListResponse>('inspections'),
  vendors: new ApiResource<VendorCreate, VendorUpdate, VendorQuery, VendorResponse, VendorListResponse>('vendors'),
  conversations: new ApiResource<ConversationCreate, ConversationUpdate, ConversationQuery, ConversationResponse, ConversationListResponse>('conversations'),
  applications: new ApiResource<ApplicationCreate, ApplicationUpdate, ApplicationQuery, ApplicationResponse, ApplicationListResponse>('applications'),
  notifications: new ApiResource<NotificationCreate, NotificationUpdate, NotificationQuery, NotificationResponse, NotificationListResponse>('notifications'),
  tasks: new ApiResource<TaskCreate, TaskUpdate, TaskQuery, TaskResponse, TaskListResponse>('tasks'),
  invitations: new ApiResource<InvitationCreate, InvitationUpdate, InvitationQuery, InvitationResponse, InvitationListResponse>('invitations'),
  generatedForms: new ApiResource<GeneratedFormCreate, GeneratedFormUpdate, GeneratedFormQuery, GeneratedFormResponse, GeneratedFormListResponse>('generated-forms'),
  units: new ApiResource<UnitCreate, UnitUpdate, UnitQuery, UnitResponse, UnitListResponse>('units'),
  landlords: new ApiResource<LandlordCreate, LandlordUpdate, LandlordQuery, LandlordResponse, LandlordListResponse>('landlords'),
  specialized: new SpecializedApi(),
};

export default v1Api;
