# Generated by Django 4.2 on 2025-11-21 23:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ticket_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('HVAC', 'HVAC/Heating/Cooling'), ('APPLIANCE', 'Appliance'), ('STRUCTURAL', 'Structural'), ('PEST_CONTROL', 'Pest Control'), ('CLEANING', 'Cleaning'), ('LANDSCAPING', 'Landscaping'), ('PAINTING', 'Painting'), ('SECURITY', 'Security'), ('OTHER', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent/Emergency')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('initiated_by', models.CharField(choices=[('TENANT', 'Tenant'), ('LANDLORD', 'Landlord'), ('PMC', 'Property Management Company')], default='TENANT', max_length=20)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_to_vendor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_to_provider_id', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tenant_approved', models.BooleanField(default=False)),
                ('landlord_approved', models.BooleanField(default=False)),
                ('created_by_pmc', models.BooleanField(default=False)),
                ('pmc_id', models.CharField(blank=True, max_length=50, null=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('before_photos', models.JSONField(blank=True, null=True)),
                ('after_photos', models.JSONField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tenant_feedback', models.TextField(blank=True, null=True)),
                ('last_viewed_by_landlord', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_by_tenant', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='property.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Maintenance Request',
                'verbose_name_plural': 'Maintenance Requests',
                'db_table': 'maintenance_requests',
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_name', models.CharField(max_length=200)),
                ('author_role', models.CharField(choices=[('TENANT', 'Tenant'), ('LANDLORD', 'Landlord'), ('VENDOR', 'Vendor'), ('PMC', 'Property Management')], max_length=20)),
                ('comment', models.TextField()),
                ('is_status_update', models.BooleanField(default=False)),
                ('old_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='maintenance.maintenancerequest')),
            ],
            options={
                'verbose_name': 'Maintenance Comment',
                'verbose_name_plural': 'Maintenance Comments',
                'db_table': 'maintenance_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['property'], name='maintenance_propert_0f8de6_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['tenant'], name='maintenance_tenant__dde1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['status'], name='maintenance_status_b8d89d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['priority'], name='maintenance_priorit_7af9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['category'], name='maintenance_categor_1e2358_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['requested_date'], name='maintenance_request_1d7aad_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['ticket_number'], name='maintenance_ticket__99e465_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancecomment',
            index=models.Index(fields=['maintenance_request'], name='maintenance_mainten_147f63_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancecomment',
            index=models.Index(fields=['created_at'], name='maintenance_created_fd59e4_idx'),
        ),
    ]
