"""
LTB Documents Constants

Single Source of Truth for Ontario Landlord and Tenant Board (LTB) forms
Source: https://tribunalsontario.ca/ltb/forms-filing-and-fees/#panel1
Last Updated: Based on official LTB website as of 2025
"""

LTB_DOCUMENTS = [
    # ===== NOTICES OF RENT INCREASE FOR LANDLORDS =====
    {
        'id': 'n1',
        'form_number': 'N1',
        'name': 'Notice of Rent Increase',
        'description': 'Use this form to officially notify your tenant that you want to increase their rent. This is the standard notice for rent increases in Ontario.',
        'category': 'Rent',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Rent%20Increase%20%26%20Instructions/N1.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Rent%20Increase%20%26%20Instructions/N1%20instructions_final_Nov30_2015.pdf',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'n2',
        'form_number': 'N2',
        'name': 'Notice of Rent Increase (Unit Partially Exempt)',
        'description': 'Use this form to notify your tenant about a rent increase if their unit is partially exempt from rent control rules (like some care homes or social housing).',
        'category': 'Rent',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Rent%20Increase%20%26%20Instructions/N2.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Rent%20Increase%20%26%20Instructions/N2%20instructions_final_Nov30_2015.pdf',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'n3',
        'form_number': 'N3',
        'name': 'Notice to Increase the Rent and/or Charges for Care Services and Meals',
        'description': 'Use this form to increase rent when you provide care services (like nursing care) or meals to your tenant as part of their rental agreement.',
        'category': 'Rent',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Rent%20Increase%20%26%20Instructions/N3.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Rent%20Increase%20%26%20Instructions/N3%20instructions_final_Nov30_2015.pdf',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'n10',
        'form_number': 'N10',
        'name': 'Agreement to Increase the Rent Above the Guideline',
        'description': 'Use this form when both you and your tenant agree to increase the rent above the annual guideline amount set by the government.',
        'category': 'Rent',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Rent%20Increase%20%26%20Instructions/N10.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Rent%20Increase%20%26%20Instructions/N10%20instructions_final_Nov30_2015.pdf',
        'country': 'CA',
        'province': 'ON',
    },
    
    # ===== NOTICES OF TERMINATION FOR LANDLORDS =====
    {
        'id': 'n4',
        'form_number': 'N4',
        'name': 'Notice to End your Tenancy Early for Non-payment of Rent',
        'description': 'Use this form to start the eviction process when your tenant hasn\'t paid their rent. This gives them a chance to pay or move out before you file with the Board.',
        'category': 'Eviction',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Termination%20%26%20Instructions/N4.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Termination%20%26%20Instructions/N4%20instructions_final_Nov30_2015.pdf',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'n5',
        'form_number': 'N5',
        'name': 'Notice to End your Tenancy for Interfering with Others, Damage or Overcrowding',
        'description': 'Use this form to start eviction when your tenant is disturbing other tenants, causing damage to the property, or has too many people living in the unit.',
        'category': 'Eviction',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Termination%20%26%20Instructions/N5.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Termination%20%26%20Instructions/N5%20instructions_final_Nov30_2015.pdf',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'n6',
        'form_number': 'N6',
        'name': 'Notice to End your Tenancy for Illegal Acts or Misrepresenting Income in a Rent-Geared-to-Income Rental Unit',
        'description': 'Use this form to evict a tenant who is doing illegal activities in the rental unit or lied about their income in a rent-geared-to-income unit.',
        'category': 'Eviction',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Termination%20%26%20Instructions/N6.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Termination%20%26%20Instructions/N6%20instructions_final_Jan2018.pdf',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'n7',
        'form_number': 'N7',
        'name': 'Notice to End your Tenancy for Causing Serious Problems in the Rental Unit or Residential Complex',
        'description': 'Use this form to evict a tenant who is causing serious problems that affect other tenants or the property, like repeated noise violations or safety issues.',
        'category': 'Eviction',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Termination%20%26%20Instructions/N7.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Termination%20%26%20Instructions/N7%20instructions_final_Nov30_2015.pdf',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'n8',
        'form_number': 'N8',
        'name': 'Notice to End your Tenancy at the End of the Term',
        'description': 'Use this form to end a tenancy when the lease term is ending and you don\'t want to renew it.',
        'category': 'Eviction',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Termination%20%26%20Instructions/N8.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Termination%20%26%20Instructions/N8%20instructions_updated_may11_2017.pdf',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'n11',
        'form_number': 'N11',
        'name': 'Agreement to End the Tenancy',
        'description': 'Use this form when both you and your tenant agree to end the rental agreement. Both parties must sign this form.',
        'category': 'Agreement',
        'audience': 'both',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Other%20Forms/N11.pdf',
        'instruction_url': None,
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'n12',
        'form_number': 'N12',
        'name': 'Notice to End your Tenancy Because the Landlord, a Purchaser or a Family Member Requires the Rental Unit',
        'description': 'Use this form to evict a tenant because you, a family member, or someone who bought the property needs to move into the rental unit.',
        'category': 'Eviction',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Termination%20%26%20Instructions/N12.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Termination%20%26%20Instructions/N12_Instructions_20200728.pdf',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'n13',
        'form_number': 'N13',
        'name': 'Notice to End your Tenancy Because the Landlord Wants to Demolish the Rental Unit, Repair it or Convert it to Another Use',
        'description': 'Use this form to evict a tenant because you need to demolish the unit, do major repairs, or convert it to a different use (like commercial space).',
        'category': 'Eviction',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Termination%20%26%20Instructions/N13.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Notices%20of%20Termination%20%26%20Instructions/N13_Instructions_20200728.pdf',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'n14',
        'form_number': 'N14',
        'name': 'Landlord\'s Notice to the Spouse of the Tenant who Vacated the Rental Unit',
        'description': 'Use this form to notify the spouse of a tenant who moved out without notice. The spouse can choose to become the new tenant or move out.',
        'category': 'Other',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Other%20Forms/N14%20-%20Landlord%27s%20Notice%20to%20the%20Spouse%20of%20the%20Tenant%20who%20Vacated%20the%20Rental%20Unit.pdf',
        'instruction_url': None,
        'country': 'CA',
        'province': 'ON',
    },
    
    # ===== APPLICATION FORMS FOR LANDLORDS =====
    {
        'id': 'l1',
        'form_number': 'L1',
        'name': 'Application to evict a tenant for non-payment of rent and to collect rent the tenant owes',
        'description': 'Use this form to file with the Board to evict a tenant who hasn\'t paid rent and to collect the money they owe you.',
        'category': 'Application',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L1.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L1_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'l2',
        'form_number': 'L2',
        'name': 'Application to End a Tenancy and Evict a Tenant or Collect Money',
        'description': 'Use this form to file with the Board to evict a tenant for various reasons (not just rent) and to collect money they owe you.',
        'category': 'Application',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L2.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L2_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'l3',
        'form_number': 'L3',
        'name': 'Application to End a Tenancy – Tenant Gave Notice or Agreed to Terminate the Tenancy',
        'description': 'Use this form to file with the Board to officially end a tenancy after your tenant gave you notice they were moving out.',
        'category': 'Application',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L3.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L3_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'l4',
        'form_number': 'L4',
        'name': 'Application to End a Tenancy and Evict a Tenant – Tenant Failed to Meet Conditions of a Settlement or Order',
        'description': 'Use this form to evict a tenant who didn\'t follow the conditions of a previous Board order or settlement agreement.',
        'category': 'Application',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L4.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L4_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'l5',
        'form_number': 'L5',
        'name': 'Application for a Rent Increase Above the Guideline',
        'description': 'Use this form to apply to the Board for permission to increase rent above the annual guideline, usually due to major repairs or renovations.',
        'category': 'Application',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L5.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L5_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'l6',
        'form_number': 'L6',
        'name': 'Application for Review of a Work Order about Provincial Maintenance Standards',
        'description': 'Use this form to challenge or review a work order from the city about maintenance standards that you disagree with.',
        'category': 'Application',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L6.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L6_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'l7',
        'form_number': 'L7',
        'name': 'Application to Transfer a Care Home Tenant',
        'description': 'Use this form to apply to transfer a tenant from one care home unit to another within your care home facility.',
        'category': 'Application',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L7.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L7_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'l8',
        'form_number': 'L8',
        'name': 'Application Because the Tenant Changed the Locks',
        'description': 'Use this form to file with the Board when your tenant changed the locks without your permission and won\'t give you a key.',
        'category': 'Application',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L8.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L8_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'l9',
        'form_number': 'L9',
        'name': 'Application to Collect Rent the Tenant Owes',
        'description': 'Use this form to file with the Board to collect unpaid rent from your current tenant without evicting them.',
        'category': 'Application',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L9.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L9_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'l10',
        'form_number': 'L10',
        'name': 'Application to Collect Money a Former Tenant Owes',
        'description': 'Use this form to file with the Board to collect money (rent, damages, etc.) from a tenant who has already moved out.',
        'category': 'Application',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L10.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/L10_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    
    # ===== APPLICATION FORMS FOR TENANTS =====
    {
        'id': 't1',
        'form_number': 'T1',
        'name': 'Tenant Application for a Rebate',
        'description': 'Use this form to apply for a rebate if your landlord charged you illegal fees, overcharged for utilities, or you paid for something you shouldn\'t have.',
        'category': 'Application',
        'audience': 'tenant',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Tenant%20Applications%20%26%20Instructions/T1.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Tenant%20Applications%20%26%20Instructions/T1_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 't2',
        'form_number': 'T2',
        'name': 'Application about Tenant Rights',
        'description': 'Use this form to file a complaint about your landlord violating your rights as a tenant, like entering without notice or harassment.',
        'category': 'Tenant Rights',
        'audience': 'tenant',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Tenant%20Applications%20%26%20Instructions/T2.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Tenant%20Applications%20%26%20Instructions/T2_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 't3',
        'form_number': 'T3',
        'name': 'Tenant Application for a Rent Reduction',
        'description': 'Use this form to apply for a rent reduction if services or facilities were removed, or if your unit became smaller or less valuable.',
        'category': 'Application',
        'audience': 'tenant',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Tenant%20Applications%20%26%20Instructions/T3.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Tenant%20Applications%20%26%20Instructions/T3_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 't4',
        'form_number': 'T4',
        'name': 'Tenant Application – Landlord did not Comply with an Agreement to Increase Rent Above the Guideline',
        'description': 'Use this form to file a complaint if your landlord didn\'t follow through on an agreement to increase rent above the guideline.',
        'category': 'Application',
        'audience': 'tenant',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Tenant%20Applications%20%26%20Instructions/T4.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Tenant%20Applications%20%26%20Instructions/T4_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 't5',
        'form_number': 'T5',
        'name': 'Tenant Application – Landlord Gave a Notice of Termination in Bad Faith',
        'description': 'Use this form to challenge an eviction notice if you believe your landlord gave it in bad faith (like saying they need it for personal use but they don\'t).',
        'category': 'Notice Response',
        'audience': 'tenant',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Tenant%20Applications%20%26%20Instructions/T5.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Tenant%20Applications%20%26%20Instructions/T5_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 't6',
        'form_number': 'T6',
        'name': 'Tenant Application about Maintenance',
        'description': 'Use this form to file a complaint about maintenance issues in your rental unit that your landlord hasn\'t fixed, like broken appliances or repairs needed.',
        'category': 'Maintenance',
        'audience': 'tenant',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Tenant%20Applications%20%26%20Instructions/T6.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Tenant%20Applications%20%26%20Instructions/T6_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 't7',
        'form_number': 'T7',
        'name': 'Tenant Application about Suite Meters',
        'description': 'Use this form to file a complaint or application about suite meters (individual utility meters) in your rental unit.',
        'category': 'Application',
        'audience': 'tenant',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Tenant%20Applications%20%26%20Instructions/T7.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Tenant%20Applications%20%26%20Instructions/T7_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    
    # ===== OTHER FORMS (BOTH LANDLORD AND TENANT) =====
    {
        'id': 'a1',
        'form_number': 'A1',
        'name': 'Application about Whether the Act Applies',
        'description': 'Use this form to ask the Board to determine if the Residential Tenancies Act applies to your situation (useful for unclear cases).',
        'category': 'Application',
        'audience': 'both',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/A1.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/A1_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'a2',
        'form_number': 'A2',
        'name': 'Application about a Sublet or an Assignment',
        'description': 'Use this form to file an application about subletting your unit to someone else or assigning your lease to another person.',
        'category': 'Application',
        'audience': 'both',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/A2.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/A2_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 'a4',
        'form_number': 'A4',
        'name': 'Application to Vary the Amount of a Rent Reduction',
        'description': 'Use this form to ask the Board to change or modify a previous rent reduction order.',
        'category': 'Application',
        'audience': 'both',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/A4.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Landlord%20Applications%20%26%20Instructions/A4_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
    {
        'id': 's3',
        'form_number': 'S3',
        'name': 'Landlord\'s Motion to Set Aside an Order to Void',
        'description': 'Use this form to ask the Board to set aside (cancel) an order that voided a previous eviction or decision.',
        'category': 'Application',
        'audience': 'landlord',
        'pdf_url': 'https://tribunalsontario.ca/documents/ltb/Other%20Forms/Landlord%27s%20Motion%20to%20Set%20Aside%20an%20Order%20to%20Void%20Form%20S3.pdf',
        'instruction_url': 'https://tribunalsontario.ca/documents/ltb/Other%20Forms/S3_Instructions.html',
        'country': 'CA',
        'province': 'ON',
    },
]


def get_ltb_documents_by_location(country, province):
    """Get LTB documents filtered by location"""
    return [doc for doc in LTB_DOCUMENTS if doc['country'] == country and doc['province'] == province]


def get_ltb_documents_by_audience(audience):
    """Get LTB documents filtered by audience"""
    if audience == 'all':
        return LTB_DOCUMENTS
    return [doc for doc in LTB_DOCUMENTS if (
        doc['audience'] == audience or 
        (audience == 'landlord' and doc['audience'] == 'both') or
        (audience == 'tenant' and doc['audience'] == 'both')
    )]


def search_ltb_documents(query):
    """Search LTB documents"""
    if not query:
        return LTB_DOCUMENTS
    lower_query = query.lower()
    return [doc for doc in LTB_DOCUMENTS if (
        lower_query in doc['form_number'].lower() or
        lower_query in doc['name'].lower() or
        (doc.get('description') and lower_query in doc['description'].lower())
    )]

