# Generated by Django 4.2 on 2025-11-22 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
        ('property', '0002_alter_property_landlord_id_alter_property_pmc_id'),
        ('lease', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_type', models.CharField(choices=[('move-in', 'Move-in'), ('move-out', 'Move-out')], db_index=True, max_length=20)),
                ('inspection_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=100, null=True)),
                ('rejected_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_checklists', to='lease.lease')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_checklists', to='property.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_checklists', to='tenant.tenant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_checklists', to='property.unit')),
            ],
            options={
                'verbose_name': 'Inspection Checklist',
                'verbose_name_plural': 'Inspection Checklists',
                'db_table': 'inspection_checklists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=100)),
                ('item_label', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('is_checked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('landlord_notes', models.TextField(blank=True, null=True)),
                ('landlord_approval', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20, null=True)),
                ('landlord_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspection.inspectionchecklist')),
            ],
            options={
                'verbose_name': 'Checklist Item',
                'verbose_name_plural': 'Checklist Items',
                'db_table': 'inspection_checklist_items',
                'ordering': ['category', 'item_id'],
            },
        ),
        migrations.AddIndex(
            model_name='inspectionchecklistitem',
            index=models.Index(fields=['checklist_id'], name='inspection__checkli_faac90_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionchecklistitem',
            index=models.Index(fields=['item_id'], name='inspection__item_id_f6e4de_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionchecklist',
            index=models.Index(fields=['tenant_id'], name='inspection__tenant__0c6122_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionchecklist',
            index=models.Index(fields=['status'], name='inspection__status_7f28b9_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionchecklist',
            index=models.Index(fields=['checklist_type'], name='inspection__checkli_f2d135_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionchecklist',
            index=models.Index(fields=['submitted_at'], name='inspection__submitt_dcd347_idx'),
        ),
    ]
