# Generated by Django 4.2 on 2025-11-22 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyManagementCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province_state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('region_code', models.CharField(blank=True, max_length=10, null=True)),
                ('default_commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Default commission rate percentage', max_digits=5, null=True)),
                ('commission_structure', models.JSONField(blank=True, help_text='Flexible commission structure configuration', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=100, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('invited_by', models.CharField(blank=True, max_length=100, null=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Management Company',
                'verbose_name_plural': 'Property Management Companies',
                'db_table': 'property_management_companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propertymanagementcompany',
            index=models.Index(fields=['email'], name='property_ma_email_88f969_idx'),
        ),
        migrations.AddIndex(
            model_name='propertymanagementcompany',
            index=models.Index(fields=['company_id'], name='property_ma_company_b27e29_idx'),
        ),
        migrations.AddIndex(
            model_name='propertymanagementcompany',
            index=models.Index(fields=['approval_status'], name='property_ma_approva_54ff6b_idx'),
        ),
        migrations.AddIndex(
            model_name='propertymanagementcompany',
            index=models.Index(fields=['is_active'], name='property_ma_is_acti_d318a6_idx'),
        ),
        migrations.AddIndex(
            model_name='propertymanagementcompany',
            index=models.Index(fields=['created_at'], name='property_ma_created_98752f_idx'),
        ),
    ]
