# Generated by Django 4.2 on 2025-11-22 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('provider_type', models.CharField(choices=[('vendor', 'Vendor'), ('contractor', 'Contractor')], db_index=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province_state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('region_code', models.CharField(blank=True, max_length=10, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_info', models.TextField(blank=True, null=True)),
                ('services', models.JSONField(blank=True, default=list, help_text='List of services provided')),
                ('specialties', models.JSONField(blank=True, default=list, help_text='Specialty areas')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=100, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('invited_by', models.CharField(blank=True, max_length=100, null=True)),
                ('invited_by_role', models.CharField(blank=True, max_length=20, null=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average rating (1-5)', max_digits=3, null=True)),
                ('total_ratings', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'db_table': 'service_providers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated_by', models.CharField(max_length=100)),
                ('rated_by_type', models.CharField(max_length=20)),
                ('rated_by_email', models.EmailField(max_length=254)),
                ('rated_by_name', models.CharField(max_length=255)),
                ('work_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('property_id', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_id', models.CharField(blank=True, max_length=100, null=True)),
                ('quality', models.IntegerField()),
                ('timeliness', models.IntegerField()),
                ('communication', models.IntegerField()),
                ('professionalism', models.IntegerField()),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='service_provider.serviceprovider')),
            ],
            options={
                'verbose_name': 'Service Provider Rating',
                'verbose_name_plural': 'Service Provider Ratings',
                'db_table': 'service_provider_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['provider_id'], name='service_pro_provide_4c9b63_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['provider_type'], name='service_pro_provide_d0d143_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['email'], name='service_pro_email_bd39fa_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['is_active'], name='service_pro_is_acti_e75e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['is_verified'], name='service_pro_is_veri_42612d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['approval_status'], name='service_pro_approva_b74ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['created_at'], name='service_pro_created_f0ae23_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceproviderrating',
            index=models.Index(fields=['service_provider_id'], name='service_pro_service_22dc6a_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceproviderrating',
            index=models.Index(fields=['rated_by'], name='service_pro_rated_b_7089df_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceproviderrating',
            index=models.Index(fields=['rated_by_type'], name='service_pro_rated_b_33cf2e_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceproviderrating',
            index=models.Index(fields=['created_at'], name='service_pro_created_c68120_idx'),
        ),
    ]
