/**
 * Generated API Handler for Unit
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated from the canonical schema registry.
 * Run `npm run generate:api-handlers` to regenerate.
 * 
 * Generated: 2025-11-18T02:40:03.900Z
 */

import { NextApiRequest, NextApiResponse } from 'next';
import { withAuth, UserContext } from '@/lib/middleware/apiMiddleware';
import { UnitService, UnitRepository } from '@/lib/domains/unit';
import { PropertyRepository } from '@/lib/domains/property';
import { unitCreateSchema, unitUpdateSchema, unitQuerySchema } from '@/lib/schemas';
const { prisma } = require('@/lib/prisma');

/**
 * API Handler for Unit CRUD operations
 */
async function handler(req: NextApiRequest, res: NextApiResponse, user: UserContext) {
  const repository = new UnitRepository(prisma);
  const propertyRepository = new PropertyRepository(prisma);
  const service = new UnitService(repository, propertyRepository);

  try {
    switch (req.method) {
      case 'GET': {
        // List Units
        if (!req.query.id) {
          const query = unitQuerySchema.parse(req.query);
          const result = await service.list({ propertyId: query.propertyId }, undefined);
          // Units returns array directly
          return res.status(200).json({
            success: true,
            data: result,
            pagination: {
              page: query.page || 1,
              limit: query.limit || 50,
              total: Array.isArray(result) ? result.length : 0,
              totalPages: Math.ceil((Array.isArray(result) ? result.length : 0) / (query.limit || 50)),
            },
          });
        }

        // Get Unit by ID
        const id = req.query.id as string;
        const item = await service.getById(id);
        if (!item) {
          return res.status(404).json({ error: 'Unit not found' });
        }
        return res.status(200).json({ success: true, data: item });
      }

      case 'POST': {
        const data = unitCreateSchema.parse(req.body);
        const created = await service.create(data, undefined);
        return res.status(201).json({ success: true, data: created });
      }

      case 'PATCH': {
        const id = req.query.id as string;
        if (!id) {
          return res.status(400).json({ error: 'ID is required' });
        }
        const data = unitUpdateSchema.parse(req.body);
        const updated = await service.update(id, data);
        return res.status(200).json({ success: true, data: updated });
      }

      case 'DELETE': {
        const id = req.query.id as string;
        if (!id) {
          return res.status(400).json({ error: 'ID is required' });
        }
        await service.delete(id);
        res.status(204).end();
        return;
      }

      default:
        return res.status(405).json({ error: 'Method not allowed' });
    }
  } catch (error: any) {
    if (error.name === 'ZodError') {
      return res.status(400).json({
        error: 'Validation error',
        details: error.issues,
      });
    }
    console.error(`[Unit API Handler] Error:`, error);
    return res.status(500).json({
      error: error.message || 'Internal server error',
    });
  }
}

export default withAuth(handler, {
  requireRole: ['landlord', 'pmc', 'admin'],
  allowedMethods: ['GET', 'POST', 'PATCH', 'DELETE'],
});
