# Generated by Django 4.2 on 2025-11-22 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landlord', '0001_initial'),
        ('rbac', '0001_initial'),
        ('pmc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('invitation_type', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant'), ('vendor', 'Vendor'), ('contractor', 'Contractor'), ('pmc', 'Property Management Company'), ('admin', 'Admin')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('opened', 'Opened'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('invited_by', models.CharField(max_length=100)),
                ('invited_by_role', models.CharField(max_length=20)),
                ('invited_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invited_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='rbac.admin')),
                ('invited_by_landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='landlord.landlord')),
                ('invited_by_pmc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='pmc.propertymanagementcompany')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'db_table': 'invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['email'], name='invitations_email_6e7169_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['token'], name='invitations_token_5b330c_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['invitation_type'], name='invitations_invitat_4a90a2_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['status'], name='invitations_status_1739b8_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['invited_by'], name='invitations_invited_a40353_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['expires_at'], name='invitations_expires_7f52c2_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['created_at'], name='invitations_created_acaa38_idx'),
        ),
    ]
