# Generated by Django 4.2 on 2025-11-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('user_name', models.CharField(max_length=255)),
                ('user_role', models.CharField(choices=[('admin', 'Admin'), ('landlord', 'Landlord'), ('pmc', 'PMC'), ('tenant', 'Tenant'), ('vendor', 'Vendor'), ('contractor', 'Contractor')], db_index=True, max_length=20)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=100)),
                ('entity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('property_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('landlord_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('pmc_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('vendor_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('contractor_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('approval_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('user_email', models.EmailField(db_index=True, max_length=254)),
                ('user_name', models.CharField(max_length=255)),
                ('user_role', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant')], db_index=True, max_length=20)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('resource', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user_id'], name='user_activi_user_id_260c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user_role'], name='user_activi_user_ro_4015f7_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['action'], name='user_activi_action_b4118c_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['created_at'], name='user_activi_created_9fa3ca_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user_email'], name='user_activi_user_em_3fcaca_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user_id'], name='activity_lo_user_id_072db3_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user_role'], name='activity_lo_user_ro_5b9ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='activity_lo_action_b49f28_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['entity_type'], name='activity_lo_entity__97ab7c_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='activity_lo_created_166e11_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['property_id'], name='activity_lo_propert_27e73a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['landlord_id'], name='activity_lo_landlor_723682_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['tenant_id'], name='activity_lo_tenant__f3e8c4_idx'),
        ),
    ]
