/**
 * Generate TypeScript Types from Zod Schemas
 * 
 * This script generates a consolidated types file from all domain schemas
 * Run with: npm run generate:types
 */

import * as fs from 'fs';
import * as path from 'path';
import { schemaRegistry } from '@/schema/types/registry';

const OUTPUT_FILE = path.join(__dirname, '../schema/types/src/generated-types.ts');

/**
 * Generate TypeScript types from schemas
 */
function generateTypes(): void {
  const imports: string[] = [];
  const typeExports: string[] = [];

  // Generate imports and type exports for each domain
  for (const [domainKey, domainDef] of Object.entries(schemaRegistry)) {
    const domainName = domainDef.domain;
    const pascalDomain = domainName
      .split('-')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join('');

    // Import schemas (handle hyphens in domain names)
    const importName = domainName.replace(/-/g, '');
    imports.push(`import * as ${importName}Schemas from './domains/${domainName}.schema';`);

    // Generate type exports - infer from schemas directly
    // Use schemaNames if provided, otherwise infer from schema object
    const schemas = domainDef.schemas;
    
    // Infer schema names from domain name and schema structure
    // schemaNames is optional, so we always provide fallbacks
    const createSchemaName = (domainDef.schemaNames?.create || `${domainName}CreateSchema`.replace(/-/g, '')) as string;
    const updateSchemaName = (domainDef.schemaNames?.update || `${domainName}UpdateSchema`.replace(/-/g, '')) as string;
    const querySchemaName = (domainDef.schemaNames?.query || `${domainName}QuerySchema`.replace(/-/g, '')) as string;
    const responseSchemaName = (domainDef.schemaNames?.response || `${domainName}ResponseSchema`.replace(/-/g, '')) as string;
    const listResponseSchemaName = (domainDef.schemaNames?.listResponse || `${domainName}ListResponseSchema`.replace(/-/g, '')) as string;
    
    // Export types directly from schemas
    typeExports.push(
      `export type ${pascalDomain}Create = z.infer<typeof ${importName}Schemas.${createSchemaName}>;`
    );
    typeExports.push(
      `export type ${pascalDomain}Update = z.infer<typeof ${importName}Schemas.${updateSchemaName}>;`
    );
    typeExports.push(
      `export type ${pascalDomain}Query = z.infer<typeof ${importName}Schemas.${querySchemaName}>;`
    );
    typeExports.push(
      `export type ${pascalDomain}Response = z.infer<typeof ${importName}Schemas.${responseSchemaName}>;`
    );
    typeExports.push(
      `export type ${pascalDomain}ListResponse = z.infer<typeof ${importName}Schemas.${listResponseSchemaName}>;`
    );
  }

  // Generate the file content
  const content = `/**
 * Generated TypeScript Types
 * 
 * ⚠️ DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated from Zod schemas.
 * Run \`npm run generate:types\` to regenerate.
 * 
 * Generated: ${new Date().toISOString()}
 */

import { z } from 'zod';

${imports.join('\n')}

${typeExports.join('\n')}
`;

  // Write to file
  fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');
  console.log(`✅ Generated types file: ${OUTPUT_FILE}`);
  console.log(`   Exported ${typeExports.length} types from ${Object.keys(schemaRegistry).length} domains`);
}

// Run generation
try {
  generateTypes();
} catch (error) {
  console.error('❌ Error generating types:', error);
  process.exit(1);
}

