# Generated by Django 4.2 on 2025-11-21 23:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField(blank=True, null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('rent_due_day', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('PENDING', 'Pending')], default='ACTIVE', max_length=20)),
                ('renewal_reminder_sent', models.BooleanField(default=False)),
                ('renewal_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_decision', models.CharField(blank=True, choices=[('RENEW', 'Renew'), ('TERMINATE', 'Terminate'), ('MONTH_TO_MONTH', 'Month to Month')], max_length=20, null=True)),
                ('renewal_decision_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_decision_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lease',
                'verbose_name_plural': 'Leases',
                'db_table': 'leases',
                'ordering': ['-lease_start'],
            },
        ),
        migrations.CreateModel(
            name='LeaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('storage_path', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lease Document',
                'verbose_name_plural': 'Lease Documents',
                'db_table': 'lease_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseTermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('initiated_by', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('termination_date', models.DateField()),
                ('actual_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('form_type', models.CharField(choices=[('N11', 'N11 - Agreement to End Tenancy'), ('N9', 'N9 - Tenant Notice to End Tenancy'), ('N15', 'N15 - Termination for Persistent Late Rent')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=50, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_by', models.CharField(blank=True, max_length=50, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='lease.lease')),
            ],
            options={
                'verbose_name': 'Lease Termination',
                'verbose_name_plural': 'Lease Terminations',
                'db_table': 'lease_terminations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_tenant', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_tenants', to='lease.lease')),
            ],
            options={
                'verbose_name': 'Lease-Tenant Relationship',
                'verbose_name_plural': 'Lease-Tenant Relationships',
                'db_table': 'lease_tenants',
            },
        ),
    ]
