# Generated by Django 4.2 on 2025-11-21 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
        ('lease', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasetenant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_leases', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='leasedocument',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lease.lease'),
        ),
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='property.unit'),
        ),
        migrations.AddIndex(
            model_name='leasetermination',
            index=models.Index(fields=['lease'], name='lease_termi_lease_i_aa9629_idx'),
        ),
        migrations.AddIndex(
            model_name='leasetermination',
            index=models.Index(fields=['status'], name='lease_termi_status_53dc05_idx'),
        ),
        migrations.AddIndex(
            model_name='leasetermination',
            index=models.Index(fields=['termination_date'], name='lease_termi_termina_fc1192_idx'),
        ),
        migrations.AddIndex(
            model_name='leasetenant',
            index=models.Index(fields=['tenant'], name='lease_tenan_tenant__abacd4_idx'),
        ),
        migrations.AddIndex(
            model_name='leasetenant',
            index=models.Index(fields=['lease'], name='lease_tenan_lease_i_5e2058_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leasetenant',
            unique_together={('lease', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='leasedocument',
            index=models.Index(fields=['lease'], name='lease_docum_lease_i_4b280e_idx'),
        ),
        migrations.AddIndex(
            model_name='leasedocument',
            index=models.Index(fields=['uploaded_at'], name='lease_docum_uploade_48881a_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['unit'], name='leases_unit_id_723755_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['status'], name='leases_status_3db7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['lease_end'], name='leases_lease_e_c4bfe7_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['renewal_reminder_sent'], name='leases_renewal_c54c87_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['created_at'], name='leases_created_8c055a_idx'),
        ),
    ]
