/**
 * Schema Index - Compatibility Layer
 * 
 * ⚠️ DEPRECATED: This file is kept for backward compatibility.
 * 
 * The canonical schemas are now in `schema/types/domains/`.
 * All types are generated from `schema/types/registry.ts`.
 * 
 * For new code, use:
 * - `import { PropertyCreate } from '@/lib/schemas';` (still works)
 * - Or: `import { PropertyCreate } from 'schema/types/src/generated-types';` (canonical)
 * 
 * To regenerate types: `npm run generate:types`
 */

// Re-export from canonical schema location
export * from '@/schema/types/base';
export * from '@/schema/types/domains/property.schema';
export * from '@/schema/types/domains/tenant.schema';
export * from '@/schema/types/domains/lease.schema';
export * from '@/schema/types/domains/rent-payment.schema';
export * from '@/schema/types/domains/maintenance.schema';
export * from '@/schema/types/domains/document.schema';
export * from '@/schema/types/domains/expense.schema';
export * from '@/schema/types/domains/inspection.schema';
export * from '@/schema/types/domains/vendor.schema';
export * from '@/schema/types/domains/conversation.schema';
export * from '@/schema/types/domains/application.schema';
export * from '@/schema/types/domains/notification.schema';
export * from '@/schema/types/domains/task.schema';
export * from '@/schema/types/domains/invitation.schema';
export * from '@/schema/types/domains/generated-form.schema';
export * from '@/schema/types/domains/unit.schema';
export * from '@/schema/types/domains/landlord.schema';
export * from '@/schema/types/domains/form-generation.schema';
export * from '@/schema/types/domains/signature.schema';
export * from '@/schema/types/domains/tenant-rent-data.schema';
export * from '@/schema/types/domains/analytics.schema';
export * from '@/schema/types/domains/search.schema';
export * from '@/schema/types/domains/activity-log.schema';

// Generated types (from canonical schema registry)
// ⚠️ DO NOT EDIT - Auto-generated by `npm run generate:types`
export * from '@/schema/types/src/generated-types';

// Re-export Zod for convenience
export { z } from 'zod';
