# Generated by Django 4.2 on 2025-11-22 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('TRIAL', 'Trial')], default='ACTIVE', max_length=20)),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_status', models.CharField(blank=True, max_length=50, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('max_properties', models.IntegerField(blank=True, null=True)),
                ('max_tenants', models.IntegerField(blank=True, null=True)),
                ('max_users', models.IntegerField(blank=True, null=True)),
                ('max_storage_gb', models.IntegerField(blank=True, null=True)),
                ('max_api_calls_per_month', models.IntegerField(blank=True, null=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=100, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('primary_color', models.CharField(default='#1890ff', max_length=7)),
                ('secondary_color', models.CharField(default='#52c41a', max_length=7)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('integrations', models.JSONField(blank=True, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
                'db_table': 'organization_settings',
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['subdomain'], name='organizatio_subdoma_e70a89_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status'], name='organizatio_status_195db0_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['plan'], name='organizatio_plan_b94df1_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['subscription_status'], name='organizatio_subscri_72b760_idx'),
        ),
    ]
