# Generated by Django 4.2 on 2025-11-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LTBDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Rent', 'Rent'), ('Eviction', 'Eviction'), ('Application', 'Application'), ('Agreement', 'Agreement'), ('Notice Response', 'Notice Response'), ('Tenant Rights', 'Tenant Rights'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], db_index=True, max_length=50)),
                ('audience', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant'), ('both', 'Both')], db_index=True, default='both', max_length=20)),
                ('pdf_url', models.URLField(help_text='Direct PDF URL from LTB website', max_length=500)),
                ('instruction_url', models.URLField(blank=True, help_text='Instructions URL', max_length=500, null=True)),
                ('country', models.CharField(db_index=True, default='CA', max_length=2)),
                ('province', models.CharField(db_index=True, default='ON', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LTB Document',
                'verbose_name_plural': 'LTB Documents',
                'db_table': 'ltb_documents',
                'ordering': ['form_number'],
            },
        ),
        migrations.AddIndex(
            model_name='ltbdocument',
            index=models.Index(fields=['country', 'province'], name='ltb_documen_country_20a08a_idx'),
        ),
        migrations.AddIndex(
            model_name='ltbdocument',
            index=models.Index(fields=['category'], name='ltb_documen_categor_522d48_idx'),
        ),
        migrations.AddIndex(
            model_name='ltbdocument',
            index=models.Index(fields=['audience'], name='ltb_documen_audienc_cf6542_idx'),
        ),
    ]
