# Generated by Django 4.2 on 2025-11-22 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0002_alter_property_landlord_id_alter_property_pmc_id'),
        ('landlord', '0001_initial'),
        ('tenant', '0001_initial'),
        ('pmc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('conversation_type', models.CharField(choices=[('LANDLORD_TENANT', 'Landlord-Tenant'), ('LANDLORD_PMC', 'Landlord-PMC'), ('TENANT_PMC', 'Tenant-PMC'), ('LANDLORD_TENANT_PMC', 'Landlord-Tenant-PMC')], default='LANDLORD_TENANT', max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20)),
                ('linked_entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('linked_entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('landlord_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('pmc_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('notify_landlord', models.BooleanField(default=True)),
                ('notify_tenant', models.BooleanField(default=True)),
                ('notify_pmc', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], max_length=20, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by_landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to='landlord.landlord')),
                ('created_by_pmc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to='pmc.propertymanagementcompany')),
                ('created_by_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to='tenant.tenant')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='landlord.landlord')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=100)),
                ('sender_role', models.CharField(max_length=20)),
                ('message_text', models.TextField()),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_by_landlord', models.BooleanField(default=False)),
                ('read_by_tenant', models.BooleanField(default=False)),
                ('read_by_pmc', models.BooleanField(default=False)),
                ('read_at_landlord', models.DateTimeField(blank=True, null=True)),
                ('read_at_tenant', models.DateTimeField(blank=True, null=True)),
                ('read_at_pmc', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message.conversation')),
                ('sender_landlord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='landlord.landlord')),
                ('sender_pmc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='pmc.propertymanagementcompany')),
                ('sender_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('storage_path', models.CharField(max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='message.message')),
            ],
            options={
                'verbose_name': 'Message Attachment',
                'verbose_name_plural': 'Message Attachments',
                'db_table': 'message_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='message.message'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='pmc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='pmc.propertymanagementcompany'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='property.property'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='tenant.tenant'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message_id'], name='message_att_message_2a1fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['uploaded_at'], name='message_att_uploade_690065_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation_id'], name='messages_convers_8904b4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_role'], name='messages_sender__d77337_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='messages_is_read_6a69c0_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted'], name='messages_is_dele_54348c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='messages_created_919c58_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['property_id'], name='conversatio_propert_7ce26f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['landlord_id'], name='conversatio_landlor_9bf0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['tenant_id'], name='conversatio_tenant__ded3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['pmc_id'], name='conversatio_pmc_id_d6e1d4_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status'], name='conversatio_status_742c74_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type'], name='conversatio_convers_29a8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['created_by'], name='conversatio_created_cff529_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='conversatio_last_me_594294_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['updated_at'], name='conversatio_updated_8d1310_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['property_id', 'landlord_id', 'tenant_id'], name='conversatio_propert_a7d574_idx'),
        ),
    ]
